### ISSUE TITLE
Stop the MainPage for Showing before the LoginPage?

### ISSUE THREAD

**Issue by melucas** [mallibone/LoginViewSample#1] opened 2019-03-03 17:47 UTC
Great example, thank you.

Is it possible to stop the MainPage from displaying prior to the switch to the LoginPage?  It happens quickly, but looks like it is flash or mistake.

Thank you

**Comment by mallibone** [comment] 2019-03-03 19:58
Hey @melucas, thanks and yeah that flash up (iOS only I assume?) is a bother. Try putting the navigation, to the login screen, into the constructor of the `MainPage` - I will have to give it a go some time to find the optimal solution. If you beat me to it, please let me know. 🙂

**Comment by melucas** [comment] 2019-03-03 20:55
@mallibone, yes, I have only tested on iOS so far.  I did a quick and dirty hack as you suggested, but I ended up with a navigation page inside a navigation page which was kind of interesting.  Two navbars at the top of the page once logged in.  I'll keep playing this week and let you know if I find a workable solution. 

My hack for the moment is to make the layout on the MainPage invisible until the user is logged in.  So, the blank page "flashing" does not look as bad.

**Comment by marcoduister** [comment] 2020-03-11 00:49
first of all great exemple.
But i was wondering if this problem has been solved?
because i'm having a similar problem. when i login it goes back to the login page and if i login again it finally goes to the mainpage. 
do you know any way to solve it??

**Comment by mallibone** [comment] 2020-03-11 06:27
@marcoduister I am guessing you are calling the navigation to login twice? If you put the navigation into the constructor you would have to either remove it in the OnAppearing or check if you have already navigated to the Login Page. Or else you will see your effect.

**Comment by marcoduister** [comment] 2020-03-11 12:18
thanks for replaying, im using your project. i tried debugging but i can't figure it out.

**Comment by mallibone** [comment] 2020-03-13 17:42
@melucas just to complete the thread - the current sample provided in the repo does not show the behaviour you are describing, when I run it locally. I guess you are putting a nav page within a nav page maybe? But since I can't reproduce this I will close this issue for now.

**Closed as completed by mallibone** 2020-03-13 17:42 UTC
Labels: enhancement, question
